version: 2

sources:
  - name: tiktok_raw
    schema: tiktok_raw
    tables:
      - name: ads_insights
        identifier: ad_report_daily
      
        freshness: 
          warn_after: {count: 24, period: hour}

        loaded_at_field: _fivetran_synced

      - name: ads
        identifier: ad_history
      - name: adgroups
        identifier: adgroup_history
      - name: campaigns
        identifier: campaign_history

models:
  - name: ads_insights 
    columns:
      - name: unique_key
        tests: 
          - unique
          - not_null